# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data Muses
tagline:          'A Jekyll theme'
description:      'A collated list of amazing Data Visualizations and Stories, I like and admire. Curated by: <br/><a href="https://twitter.com/gggodhwani" target="_blank">Gaurav Godhwani</a>'
baseurl:          /

author:
  name:           'Gaurav Godhwani'
  url:            https://twitter.com/gggodhwani

paginate:         5

# Custom vars
version:          0.1
github:
  repo:           https://github.com/gggodhwani/data_muses
